### ISSUE TITLE
AntiVM

### ISSUE THREAD

**Issue by blackteam1** [Back-X/anti-vm#1]
this is all great, but there is one thing, but this code simply determines the real PC or it is a virtual machine, but the program still continues to work even if it was determined that it is a virtual machine

**Comment by graysuit** [comment]
@blackteam1  
Code is very tiny. You can easily change it to close if VM found.
like if VM detected, close app. That;s it.

By the way, which code you were using ?

**Comment by blackteam1** [comment]
bool IsVM = (new System.Management.ManagementObjectSearcher("SELECT * FROM Win32_PortConnector")).Get().Count == 0;
		MessageBox.Show
		(
		    "You are using " + (IsVM ? "Virtual" : "Real") + " Environment", 
			"Universal VM Detector", 
			MessageBoxButtons.OK, 
			(IsVM ? MessageBoxIcon.Warning : MessageBoxIcon.Information)
	    );

here is the code I used, but can you tell me how to make the program close if it was determined that this is a virtual machine? I would be very grateful

**Comment by graysuit** [comment]
```csharp
bool IsVM = (new System.Management.ManagementObjectSearcher("SELECT * FROM Win32_PortConnector")).Get().Count == 0;
if(IsVM) Environment.Exit(0); //exit if VM found

//bottom lines will run if VM NOT detected   
```

**Comment by blackteam1** [comment]
Thanks!
