### ISSUE TITLE
support for java

### ISSUE THREAD

**Issue by pp0236** [Back-X/anti-vm#5]
lib: https://github.com/profesorfalken/WMI4Java
(idk how to use pull request )

```
import javax.swing.JOptionPane;

import com.profesorfalken.wmi4java.WMI4Java;
import com.profesorfalken.wmi4java.WMIClass;

public static void main(String... args) {
	boolean IsVM = (WMI4Java.get().VBSEngine().getWMIObject(WMIClass.WIN32_PORTCONNECTOR).size() == 0);
	JOptionPane.showConfirmDialog(null, "You are using " + (IsVM ? "Virtual" : "Real") + " Environment", "Universal VM Detector", -1);
}
```

**Comment by graysuit** [comment]
Hi thanks for contribution, I appreciate. 

Current code looks fine. But library doesn't look to be good ([why](https://github.com/profesorfalken/WMI4Java#how-it-works)) as it invokes wmi from powershell or either VBscript. It will triggers anti virus.

Can you make it to use some lib that isn't dependent upon powershell/VBscript or any other executable.
Native system library (*.dll) dependency is acceptable.

or else no problem. I'm free to accept change as it may helpful to java folks.

To create pull request, first fork the repo. Create and write code to `anti_vm.java` under `/windows`.
Go to pull request, and click [compare](https://github.com/Back-X/anti-vm/compare). 
Select your fork to be merge here.

**Comment by pp0236** [comment]
thanks for reply,
i'll search the ways to use dll in java 😊
